# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cli_plugin_pb2 as cli__plugin__pb2


class CLIStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Discover = channel.unary_unary(
                '/CLI/Discover',
                request_serializer=cli__plugin__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=cli__plugin__pb2.DiscoverResponse.FromString,
                )
        self.Exec = channel.unary_stream(
                '/CLI/Exec',
                request_serializer=cli__plugin__pb2.ExecRequest.SerializeToString,
                response_deserializer=cli__plugin__pb2.ExecResponse.FromString,
                )


class CLIServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CLIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=cli__plugin__pb2.DiscoverRequest.FromString,
                    response_serializer=cli__plugin__pb2.DiscoverResponse.SerializeToString,
            ),
            'Exec': grpc.unary_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=cli__plugin__pb2.ExecRequest.FromString,
                    response_serializer=cli__plugin__pb2.ExecResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CLI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CLI(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CLI/Discover',
            cli__plugin__pb2.DiscoverRequest.SerializeToString,
            cli__plugin__pb2.DiscoverResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/CLI/Exec',
            cli__plugin__pb2.ExecRequest.SerializeToString,
            cli__plugin__pb2.ExecResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
