# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cli-plugin.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cli-plugin.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\n.;protoDef',
  serialized_pb=b'\n\x10\x63li-plugin.proto\"\x11\n\x0f\x44iscoverRequest\"8\n\x10\x44iscoverResponse\x12$\n\x08\x43ommands\x18\x01 \x03(\x0b\x32\x12.CommandDefinition\"~\n\x0b\x43ommandFlag\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x10\n\x08Required\x18\x02 \x01(\x08\x12\x11\n\tShorthand\x18\x03 \x01(\t\x12\x0c\n\x04Type\x18\x04 \x01(\t\x12\r\n\x05Usage\x18\x05 \x01(\t\x12\x0f\n\x07Options\x18\x06 \x03(\t\x12\x0e\n\x06Prompt\x18\x07 \x01(\t\"Z\n\x11\x43ommandDefinition\x12\x0b\n\x03Use\x18\x01 \x01(\t\x12\r\n\x05Short\x18\x02 \x01(\t\x12\x0c\n\x04Long\x18\x03 \x01(\t\x12\x1b\n\x05\x46lags\x18\x04 \x03(\x0b\x32\x0c.CommandFlag\",\n\x0b\x45xecRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\".\n\x0c\x45xecResponse\x12\x0e\n\x06stdout\x18\x01 \x01(\x0c\x12\x0e\n\x06stderr\x18\x02 \x01(\x0c\x32]\n\x03\x43LI\x12/\n\x08\x44iscover\x12\x10.DiscoverRequest\x1a\x11.DiscoverResponse\x12%\n\x04\x45xec\x12\x0c.ExecRequest\x1a\r.ExecResponse0\x01\x42\x0cZ\n.;protoDefb\x06proto3'
)




_DISCOVERREQUEST = _descriptor.Descriptor(
  name='DiscoverRequest',
  full_name='DiscoverRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=37,
)


_DISCOVERRESPONSE = _descriptor.Descriptor(
  name='DiscoverResponse',
  full_name='DiscoverResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Commands', full_name='DiscoverResponse.Commands', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=95,
)


_COMMANDFLAG = _descriptor.Descriptor(
  name='CommandFlag',
  full_name='CommandFlag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='CommandFlag.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Required', full_name='CommandFlag.Required', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Shorthand', full_name='CommandFlag.Shorthand', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Type', full_name='CommandFlag.Type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Usage', full_name='CommandFlag.Usage', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Options', full_name='CommandFlag.Options', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Prompt', full_name='CommandFlag.Prompt', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=223,
)


_COMMANDDEFINITION = _descriptor.Descriptor(
  name='CommandDefinition',
  full_name='CommandDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Use', full_name='CommandDefinition.Use', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Short', full_name='CommandDefinition.Short', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Long', full_name='CommandDefinition.Long', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Flags', full_name='CommandDefinition.Flags', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=315,
)


_EXECREQUEST = _descriptor.Descriptor(
  name='ExecRequest',
  full_name='ExecRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='ExecRequest.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='ExecRequest.args', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=361,
)


_EXECRESPONSE = _descriptor.Descriptor(
  name='ExecResponse',
  full_name='ExecResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stdout', full_name='ExecResponse.stdout', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stderr', full_name='ExecResponse.stderr', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=409,
)

_DISCOVERRESPONSE.fields_by_name['Commands'].message_type = _COMMANDDEFINITION
_COMMANDDEFINITION.fields_by_name['Flags'].message_type = _COMMANDFLAG
DESCRIPTOR.message_types_by_name['DiscoverRequest'] = _DISCOVERREQUEST
DESCRIPTOR.message_types_by_name['DiscoverResponse'] = _DISCOVERRESPONSE
DESCRIPTOR.message_types_by_name['CommandFlag'] = _COMMANDFLAG
DESCRIPTOR.message_types_by_name['CommandDefinition'] = _COMMANDDEFINITION
DESCRIPTOR.message_types_by_name['ExecRequest'] = _EXECREQUEST
DESCRIPTOR.message_types_by_name['ExecResponse'] = _EXECRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiscoverRequest = _reflection.GeneratedProtocolMessageType('DiscoverRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISCOVERREQUEST,
  '__module__' : 'cli_plugin_pb2'
  # @@protoc_insertion_point(class_scope:DiscoverRequest)
  })
_sym_db.RegisterMessage(DiscoverRequest)

DiscoverResponse = _reflection.GeneratedProtocolMessageType('DiscoverResponse', (_message.Message,), {
  'DESCRIPTOR' : _DISCOVERRESPONSE,
  '__module__' : 'cli_plugin_pb2'
  # @@protoc_insertion_point(class_scope:DiscoverResponse)
  })
_sym_db.RegisterMessage(DiscoverResponse)

CommandFlag = _reflection.GeneratedProtocolMessageType('CommandFlag', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDFLAG,
  '__module__' : 'cli_plugin_pb2'
  # @@protoc_insertion_point(class_scope:CommandFlag)
  })
_sym_db.RegisterMessage(CommandFlag)

CommandDefinition = _reflection.GeneratedProtocolMessageType('CommandDefinition', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDDEFINITION,
  '__module__' : 'cli_plugin_pb2'
  # @@protoc_insertion_point(class_scope:CommandDefinition)
  })
_sym_db.RegisterMessage(CommandDefinition)

ExecRequest = _reflection.GeneratedProtocolMessageType('ExecRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXECREQUEST,
  '__module__' : 'cli_plugin_pb2'
  # @@protoc_insertion_point(class_scope:ExecRequest)
  })
_sym_db.RegisterMessage(ExecRequest)

ExecResponse = _reflection.GeneratedProtocolMessageType('ExecResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXECRESPONSE,
  '__module__' : 'cli_plugin_pb2'
  # @@protoc_insertion_point(class_scope:ExecResponse)
  })
_sym_db.RegisterMessage(ExecResponse)


DESCRIPTOR._options = None

_CLI = _descriptor.ServiceDescriptor(
  name='CLI',
  full_name='CLI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=411,
  serialized_end=504,
  methods=[
  _descriptor.MethodDescriptor(
    name='Discover',
    full_name='CLI.Discover',
    index=0,
    containing_service=None,
    input_type=_DISCOVERREQUEST,
    output_type=_DISCOVERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Exec',
    full_name='CLI.Exec',
    index=1,
    containing_service=None,
    input_type=_EXECREQUEST,
    output_type=_EXECRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLI)

DESCRIPTOR.services_by_name['CLI'] = _CLI

# @@protoc_insertion_point(module_scope)
